### ISSUE TITLE
Implementation of nested skills

### ISSUE THREAD

**Issue by maikenp** [neicnordic/knowledge-map#3]
As discussed with @vingar and @caela we want to categorize the skills in the following way

```
skills:
   - prog_lang:
      - python
      - c++
      - someprog 
   - skilltype2:
      - pps
      - cmake
```

At the moment expanded the skills_found to a dictionary instead of a list as it was before. 
I am also printing out the people found - I think that makes sense, not only to see where people are in the map. But we can discuss this. 

What I implemented also is a dictionary holding the skill-keys and values, so instead of showing the skill-key in the All skills section one can have a more meaningful and prettier category:  
{'prog_lang':'Programming languages','skilltype2':'Some other skill'} 

This is how it looks with the changes implemented: 
<img width="606" alt="Screen Shot 2020-01-24 at 21 37 26" src="https://user-images.githubusercontent.com/22190352/73102278-cf0d0980-3ef1-11ea-8847-fd0ac8e9b70b.png">

Merge request: #2
